version: '3.8'
services:
  db:
    image: postgres
    restart: always
    container_name: harmonie_db
    ports:
      - '5444:5432'
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: harmonie
    volumes:
      - /data/apps/harmonie/db_data:/var/lib/postgresql/data
    networks:
      - homelab

  backend:
    image: ghcr.io/jolyanem/707_harmonie-backend
    restart: always
    container_name: harmonie_backend
    environment:
      DATABASE_URL: ${DATABASE_URL}
    networks:
      - homelab
    labels:
      - traefik.enable=true
      - traefik.http.routers.harmonie-api.rule=Host(`harmonie-api.raphael-catarino.fr`)
      - traefik.http.services.harmonie-api.loadbalancer.server.port=3000
      - traefik.http.routers.harmonie-api.tls=true
      - traefik.http.routers.harmonie-api.tls.certresolver=production
      - traefik.http.routers.harmonie-api.tls.domains[0].main=raphael-catarino.fr
      - traefik.http.routers.harmonie-api.tls.domains[0].sans=*.raphael-catarino.fr

  frontend:
    image: ghcr.io/jolyanem/707_harmonie-frontend
    restart: always
    container_name: harmonie_frontend
    networks:
      - homelab
    labels:
      - traefik.enable=true
      - traefik.http.routers.harmonie.rule=Host(`harmonie.raphael-catarino.fr`)
      - traefik.http.services.harmonie.loadbalancer.server.port=80
      - traefik.http.routers.harmonie.tls=true
      - traefik.http.routers.harmonie.tls.certresolver=production
      - traefik.http.routers.harmonie.tls.domains[0].main=raphael-catarino.fr
      - traefik.http.routers.harmonie.tls.domains[0].sans=*.raphael-catarino.fr

networks:
  homelab:
    external: true
